# Generated by Django 4.2.5 on 2023-09-29 07:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_rename_vote_to_skip_room_votes_to_skip"),
    ]

    operations = [
        migrations.RenameField(
            model_name="room",
            old_name="create_at",
            new_name="created_at",
        ),
    ]
