# Generated by Django 4.2.5 on 2023-09-29 08:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0003_rename_create_at_room_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="room",
            name="votes_to_skip",
            field=models.IntegerField(default=1),
        ),
    ]
